config/routes.rb
Rails.application.routes.draw do

  # Map controller's index action
  # Homepage
  root to: "map#index"

  # Map
  get 'map/index'
  
  # Default routes are used so far.
  resources :countries, controller: 'countries' do
    resources :elites
  end
  resources :elites, controller: 'elites'
  resources :people, controller: 'people'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
    self.table_name = "Countries"
    validates_presence_of :Name

    has_many :elites, foreign_key: :CountryId
    
    # Get elites for country
    def get_elites ; Elite.where({CountryId: self.Id}) ; end

    # returns documents for country through associated elites for that country.
    def get_documents
        return Elite.where(CountryId: self.Id).map(&:files).flatten
    end
    
end

app/models/db_file.rb
class DBFile < ApplicationRecord
    self.table_name = "Files"
    
    validates_presence_of :Date
    #after_initialize :readonly!

    # File Type
    belongs_to :file_type       , foreign_key: :TypeId
    
    # File languages
    has_many   :file_languages  , foreign_key: :FileId      , class_name: "Relations::FileLanguage"
    has_many   :languages       , through: :file_languages
    
    # Elites
    has_many   :elite_documents , foreign_key: :FileId , class_name: "Relations::EliteDocument"
    # Comment these out
    has_many   :elites          , through: :elite_documents
    
    # People
    has_many  :person_documents , foreign_key: :FileId , class_name: "Relations::PersonDocument"
    has_many  :people           , through: :person_documents
end

app/models/elite.rb
class Elite < ApplicationRecord
    self.table_name = "Elites"
    validates_presence_of :CountryId, :Name, :TypeId

    # One to one relationships
    belongs_to :country      , foreign_key: :CountryId
    belongs_to :elite_type   , foreign_key: :TypeId
    
    # Many Files
    has_many :elite_documents, foreign_key: :EliteId    , class_name: "Relations::EliteDocument"
    has_many :files          , through: :elite_documents, class_name: "DBFile"
    
    # People Elites
    has_many :people_elites  , foreign_key: :EliteId, class_name: "PeopleElite"
end

app/models/elite_type.rb
class EliteType < ApplicationRecord
    self.table_name = "EliteTypes"
    validates_presence_of :Name
    # Read only from database
    after_initialize :readonly!
    
    # One elite type for many elites
    has_many :elites, foreign_key: :TypeId
end

app/models/file_type.rb
class FileType < ApplicationRecord
    self.table_name = "FileTypes"
    validates_presence_of :Name
    
    after_initialize :readonly!
    
    has_many :files, foreign_key: :TypeId, class_name: "DBFile"
end

app/models/language.rb
class Language < ApplicationRecord
    self.table_name = "Languages"
    validates_presence_of :Name
    
    # Read only from the database
    after_initialize :readonly!
    
    has_many :file_languages, foreign_key: :LanguageId, class_name: "Relations::FileLanguage"
    has_many :files, through: :file_languages, class_name: "DBFile"
end

app/models/nationality.rb
class Nationality < ApplicationRecord
    self.table_name = "Nationalities"
    validates_presence_of :Country, :NationalityAdjective
    
    has_many :person_nationalities, foreign_key: :NationalityId        , class_name: "Relations::PersonNationality"
    has_many :people              , through: :person_nationalities, class_name: "Person"

end

app/models/people_elite.rb
class PeopleElite < ApplicationRecord
    self.table_name = "PeopleElites"
    validates_presence_of :DateOfEmployment, :DateOfResignation, :EliteId, :MapVisible, :PersonId, :Position
    
    belongs_to :elite           , foreign_key: :EliteId
    belongs_to :person          , foreign_key: :PersonId
    
end

app/models/person.rb
class Person < ApplicationRecord
    self.table_name = "People"

    validates_presence_of :DateOfBirth, :DateOfBirth, :Name, :Surname
    
    # Nationalities
    has_many :person_nationalities  , foreign_key: :PersonId, class_name: "Relations::PersonNationality"
    has_many :nationalities         , through: :person_nationalities

    #Documents
    has_many :person_documents      , foreign_key: :PersonId, class_name: "Relations::PersonDocument"
    has_many :files                 , through: :person_documents

    # Elites
    has_many :people_elites         , foreign_key: :PersonId
    
    # OtherPerson
    has_many :person_persons        , foreign_key: :PersonId, class_name: "Relations::PersonPerson"
    
    # Selects related person entities
    def people
        Person.find_by_sql(
            "SELECT p.* FROM \"People\" p
            LEFT JOIN \"PersonPerson\" r1 
                ON p.\"Id\" = r1.\"PersonId\" 
                AND r1.\"OtherPersonId\" = #{self.Id}
            LEFT JOIN \"PersonPerson\" r2
                ON p.\"Id\" = r2.\"OtherPersonId\" 
                AND r2.\"PersonId\" = #{self.Id}
            WHERE r1.\"PersonId\" IS NOT NULL OR r2.\"PersonId\" IS NOT NULL;"
        )
    end
    
    def get_full_name
        return self.Name + " " + self.Surname
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
    #Overwrites the default "application" layout
    layout "country"

    def show
        
        @country = Country.find(params[:id])
        # Load view after assigning the variable
        
        # Documents for country
        @documents = @country.get_documents

        # Render view for country.
        # Declare instance variables first.
        render('show')
        # Test
        #@country = Country.find(1)
    end

end

app/controllers/elites_controller.rb
# Inherits from 'CountriesController'
class ElitesController < ApplicationController
    #Overwrites the default "application" layout
    layout "country"
    # Find country for elite
    
    before_action :find_country, except: :download_pdf

    def index
        @elites = @country.elites
    end

    def show
        @elite = Elite.find(params[:id])
    end
    
    # Download file from public folder
    def download_pdf()
        send_file(
          "#{Rails.root}/public/DOC 0001 DSC06246.pdf",
          filename: "DOC 0001 DSC06246",
          type: "application/pdf"
        )
    end

    private 

    def find_country
        # Find country for elite  
       @country = Country.find(params[:country_id])   
    end 
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  # Define layout here
  # Override default application layout
  layout "map"
  
  #layout :select_layout
  
  def select_layout
    case action_name
    when "map"
      "map"
    when "country"
      "country"
    else
      "application"
    end
  end


  def index
    # To act as index page.
  end

  
end

app/controllers/paneur_controller.rb
class PaneurController < ApplicationController
  # Define layout here
  # Override default application layout
  layout "map"
  
  #layout :select_layout
  
  def select_layout
    case action_name
    when "map"
      "map"
    when "country"
      "country"
    else
      "application"
    end
  end


  def map
    # To act as index page.
  end

  
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
    layout 'country'
    
    # Layout 'country' uses the @country instance variable
    
    # This method is called before the show action
    # Returns the @country instance variable
    before_action :find_country_for_person
    
    def show
        # Get single person from database using personID
        @person = Person.find(params[:id])
        # Used for the related people content
        @related_people = @person.people
        render('show')
    end
    
    def find_country_for_person()
        # Gets CountryID through Elite,
        # Gets EliteId through PeopleElite
        # Gets PeopleElite based on PersonId
        # ------------------------        
        # Note - Person must be associated with a PeopleElite object
        # Change if not all person entities are connected to a PeopleElite entity
        if PeopleElite.find_by(PersonId: params[:id]) != nil
            @country = Country.find(Elite.find(PeopleElite.find_by(PersonId: params[:id]).EliteId).CountryId)
        else
            @country = Country.first
        end
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Penguin Soldier</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/country.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title><%= yield :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="keywords" content="" >
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <!-- Web Fonts  -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800%7CShadows+Into+Light" rel="stylesheet" type="text/css">

    <!-- Link stylesheets here -->
    <%= stylesheet_link_tag('theme') %>
    <%= stylesheet_link_tag('theme-elements') %>
    <%= stylesheet_link_tag('theme-animate') %>
    <script>
		document.addEventListener("touchstart", function () {}, true);
	</script>
    
</head>

<body>
    <div class="body">
        <%= render "layouts/shared/info_header" %>
        <!-- Top navigation bar -->
        <!-- Responsive. Displays only narrow screen width only -->
        <%= render "layouts/shared/xs_sm_country_nav" %>

        <!-- Bottom navigation bar -->
        <%= render "layouts/shared/bottom_nav" %>

        <!-- FINE NAVIGAZIONE FISSA FOOTER (RESPONSIVE) -->
        <!-- Start of yield -->
        <div class="container">

            <div class="row">
                <div class="col-md-9">
                    <%= yield :content %>
                </div>
                <div class="col-md-3 hidden-xs hidden-sm">
                    <%= render "layouts/shared/country_nav" %>
                </div>
                <div style="padding-top:50px;"></div>
            </div>
        </div>
        <%= render "layouts/shared/footer" %>
    </div>
</body>

</html>

app/views/layouts/map.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Map View</title>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="keywords" content="" />
		<meta name="description" content="">
		<meta name="author" content="">

		
		<!-- Mobile Metas -->
		<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
		
		<!-- Web Fonts  -->
		<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800%7CShadows+Into+Light" rel="stylesheet" type="text/css">
    
    <!-- Link stylesheets here -->
    <%= stylesheet_link_tag('theme') %>
    <%= stylesheet_link_tag('theme-elements') %>
    <%= stylesheet_link_tag('theme-animate') %>
  </head>

  <body>
    <!-- NAVIGAZIONE FISSA FOOTER (RESPONSIVE) -->
    <nav class="navbar navbar-inverse navbar-fixed-bottom navbar-right  botmenutrasparente">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li class="botmenu">
                        <a href="about.html">ABOUT THIS MAP</a>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li class="botmenu">
                        <!-- <a href="index.html">Main map</a> -->
                        <%= link_to('Main Map', {action: 'index'})%>
                    </li>
                    <li class="dropdown botmenu">
                        <a class="dropdown-toggle active" data-toggle="dropdown" href="#">Countries
                            <span class="caret"></span>
                        </a>
                        <!-- Loop to create the dropdown menu items -->
                        <ul class="dropdown-menu">
                            <!-- Ordered by name -->
                            <% Country.all.order(:Name).each do |country| %>
                                <li class="botsubmenu">
                                    <%= link_to country.Name, country  %>
                                </li>
                            <% end %>
                        </ul>
                    </li>
                    <li class="botmenu">
                        <a href="comecon.html">Comecon</a>
                    </li>
                    <li class="botmenu">
                        <%= link_to('PanEur1970s website', 'https://paneur1970s.eui.eu/')%>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

        <!-- FINE NAVIGAZIONE FISSA FOOTER (RESPONSIVE) -->
    <!-- Start of yield -->
    <%= yield %>
    <!-- End of yield -->
  </body>
</html>

app/views/layouts/person.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Person:
        <%= yield :name %>
    </title>
    <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
            <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

                <meta name="keywords" content="" />
                <meta name="description" content="">
                <meta name="author" content="">


                <!-- Mobile Metas -->
                <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

                <!-- Web Fonts  -->
                <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800%7CShadows+Into+Light" rel="stylesheet" type="text/css">

                <!-- Link stylesheets here -->
                <%= stylesheet_link_tag('theme') %>
                    <%= stylesheet_link_tag('theme-elements') %>
                        <%= stylesheet_link_tag('theme-animate') %>
</head>

<body>
    <div class="body">
        
        <!-- Fixed nav bottom -->
        <%= render("layouts/shared/bottom_nav")%>
            <div class="container">
                <div class="row">
                    <div class="col-md-9">
                        <%= yield :content %>
                            <script>
                                function goBack() {
                                    window.history.go(-1);
                                }
                            </script>
                            <div class="row rowmega" id="overview">
                                <div class="titolomega col-md-8 hidden-xs hidden-sm" style="text-align: left; padding-left: 20px; font-size: 20px;">
                                    <a href="#" onClick="history.go(-1); return false;" style="color: #fff; text-decoration:none; padding-left:80px;">&#8592; Back</a>
                                </div>
                                <div class="titolomega2 col-md-4 hidden-xs hidden-sm">
                                    <%= @person.Name + " " + @person.Surname %>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="row">
                                    <div class="col-md-9 col-xs-7 col-sm-8">
                                        <div class="shortlife">
                                            <%= @person.Description %>(Budapest, 1934 - Warsaw, 1990)
                                                <br/> Professor of international political economy - Corvinus University of Budapest
                                        </div>
                                    </div>
                                    <div class="col-md-3 col-xs-5 col-sm-4">
                                        <!-- Add class, adding 100% width property. -->
                                        <%= image_tag('person.jpg') %>
                                    </div>

                                </div>
                                <div class="panel-group" id="accordion">

                                    <%= yield :short_bio %>
                                        <div class="panel panel-default">
                                            <div class="panel-heading">
                                                <h4 class="panel-title">
                                                    <a class="accordion-toggle" data-panel="2" data-toggle="collapse" data-parent="#accordion" href="#collapse1Two">
                                                        Relations
                                                    </a>
                                                </h4>
                                            </div>
                                            <div id="collapse1Two" class="accordion-body collapse">
                                                <div class="panel-body">
                                                    <%= yield :related_people %>
                                                </div>
                                            </div>
                                        </div>
                                        <div id "accordion" class="panel panel-default">
                                            <div class="panel-heading">
                                                <h4 class="panel-title">
                                                    <a class="accordion-toggle" data-panel="1" data-toggle="collapse" data-parent="#accordion" href="#collapse1Three">
                                                        Documents
                                                    </a>
                                                </h4>
                                            </div>
                                            <div id="collapse1Three" class="accordion-body collapse">
                                                <div class="panel-body">
                                                    <%= yield :documents %>
                                                </div>
                                            </div>
                                        </div>
                                </div>
                            </div>
                    </div>
                    <div style="padding-top:50px;"></div>
                </div>
            </div>
</body>

</html>

app/views/layouts/shared/_bottom_nav.html.erb
<!-- NAVIGAZIONE FISSA FOOTER (RESPONSIVE) -->
<nav class="navbar navbar-inverse navbar-fixed-bottom navbar-right  botmenutrasparente">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li class="botmenu">
                    <a href="about.html">ABOUT THIS MAP</a>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="botmenu">
                    <%= link_to 'Main Map', '/'%>
                </li>
                <li class="dropdown botmenu">
                    <a class="dropdown-toggle active" data-toggle="dropdown" href="#">Countries
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <% Country.all.order(:Name).each do |country| %>
                            <li class="botsubmenu">
                                <%= link_to country.Name, country  %>
                            </li>
                        <% end %>
                    </ul>
                </li>
                <li class="botmenu">
                    <a href="comecon.html">Comecon</a>
                </li>
                <li class="botmenu">
                    <%= link_to('PanEur1970s website', 'https://paneur1970s.eui.eu/')%>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/shared/_country_nav.html.erb
<aside class="sidebar" id="sidebar" data-plugin-sticky data-plugin-options='{"minWidth": 991, "containerSelector": ".container", "padding": {"top": 30}}'>
    <div class="nomepaese">
        <%= yield :name %>
    </div>
    <%= image_tag("Hungary.png", class: 'country-img')%>
    <div class="titolo">
        <%= link_to("Overview", country_path(@country, :anchor => "overview"), :class => "country-nav-header") %>
    </div>
    <ul class="nav nav-list mb-xl show-bg-active">
        <li>
            <div id="subli" style="padding-top:10px;">
                <!-- <a data-hash data-hash-offset="30" href="#archival">Archival sources</a> -->
                <%= link_to("Archival Sources", country_path(@country, :anchor => "archival")) %>
            </div>
        </li>
    </ul>  
    <div class="titolobn">
        <%= link_to("Elite Groups", country_elites_path(@country), :class => "country-nav-header") %>
    </div>
    <ul class="nav nav-list mb-xl show-bg-active2">
        <% grouped_elites = @country.elites.map{|x| [x.elite_type.Name, x] }.sort_by(&:first) %>
        <% grouped_elites.each do |type, elite| %>
            <li>
                <%= link_to elite.Name, country_elite_path(:country_id => @country.id, :id => elite.id) %>
            </li>
        <% end %>
    </ul>
</aside>

app/views/layouts/shared/_footer.html.erb
<footer id="footer">
	<div class="container">
		<div class="row">

			<div class="col-md-12">
				<div>

					<p>&copy; copyright info</p>

				</div>
			</div>
		</div>
	</div>

</footer>

app/views/layouts/shared/_info_header.html.erb
<header id="header" data-plugin-options='{"stickyEnabled": true, "stickyEnableOnBoxed": true, "stickyEnableOnMobile": true, "stickyStartAt": 57, "stickySetTop": "-57px", "stickyChangeLogo": true}'>
</header>
<section class="page-header">
    <div role="main" class="main">
        <div class="hidden-xs hidden-sm container">
            <div class="row">
                <div class="col-md-6">
                    <%= image_tag('dep.svg', class: 'dep-img') %>
                </div>
                <div class="col-md-6 text-align-right" style="font-size:10px; line-height:14px; vertical-align:middle;">
                    <%= image_tag('erc.svg', class: 'erc-img') %>
                        This project has received funding from the European Research Council under the European Union’s Horizon 2020 research and
                        innovation programme
                        <br/> (Grant Agreement n. 669194)
                </div>
            </div>
        </div>
    </div>
</section>

app/views/layouts/shared/_xs_sm_country_nav.html.erb
<span class="visible-xs visible-sm">
    <nav class="navbar navbar-inverse navbar-fixed-top  topmenutrasparente">
        <div class="container-fluid">
            <div class="navbar-header">
                <span class="navbar-brand topmenu">
                    <%= @country.Name %>
                </span>
                <!-- Toggle menu icon -->
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbartop">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="myNavbartop">

                <ul class="nav navbar-nav navbar-right">
                    <li class="topmenu">
                        <%= link_to("Overview", country_path(@country, :anchor => "Overview")) %>
                    </li>
                    <li class="topmenu">
                        <%= link_to("Archival Sources", country_path(@country, :anchor => "Archival Sources")) %>
                    </li>
                    <li class="dropdown topmenu">
                        <a class="dropdown-toggle active" data-toggle="dropdown" href="elitegroups.html"> Elite groups
                            <span class="caret"></span>
                        </a>
                        
                        <ul class="dropdown-menu">
                            <li class="topsubmenured">
                                <%= link_to "Main page", country_elites_path(:country_id => @country.id) %>
                            </li>
                            <% grouped_elites = @country.elites.map{|x| [x.elite_type.Name, x] }.sort_by(&:first) %>
                            <% grouped_elites.each do |type, elite| %>
                                <li class="topsubmenu">
                                    <!-- <%= link_to type, elite %> -->
                                    <!-- Elite for country - single element -->
                                    <%= link_to(elite.Name, country_elite_path(@country, elite)) %>
                                </li>
                            <% end %>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</span>