config/routes.rb
Rails.application.routes.draw do

  # Map controller's index action
  # Homepage
  root to: "map#index"

  # Map
  get 'map/index'
  
  # Default routes are used so far.
  resources :countries, controller: 'countries' do
    resources :elites
  end
  resources :elites, controller: 'elites'
  resources :people, controller: 'people'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/elite.rb
class Elite < ApplicationRecord
    self.table_name = "Elites"
    validates_presence_of :CountryId, :Name, :TypeId

    # One to one relationships
    belongs_to :country      , foreign_key: :CountryId
    belongs_to :elite_type   , foreign_key: :TypeId
    
    # Many Files
    has_many :elite_documents, foreign_key: :EliteId    , class_name: "Relations::EliteDocument"
    has_many :files          , through: :elite_documents, class_name: "DBFile"
    
    # People Elites
    has_many :people_elites  , foreign_key: :EliteId, class_name: "PeopleElite"
end

app/models/elite_type.rb
class EliteType < ApplicationRecord
    self.table_name = "EliteTypes"
    validates_presence_of :Name
    # Read only from database
    after_initialize :readonly!
    
    # One elite type for many elites
    has_many :elites, foreign_key: :TypeId
end

app/controllers/elites_controller.rb
# Inherits from 'CountriesController'
class ElitesController < ApplicationController
    #Overwrites the default "application" layout
    layout "country"
    # Find country for elite
    
    before_action :find_country, except: :download_pdf

    def index
        @elites = @country.elites
    end

    def show
        @elite = Elite.find(params[:id])
    end
    
    # Download file from public folder
    def download_pdf()
        send_file(
          "#{Rails.root}/public/DOC 0001 DSC06246.pdf",
          filename: "DOC 0001 DSC06246",
          type: "application/pdf"
        )
    end

    private 

    def find_country
        # Find country for elite  
       @country = Country.find(params[:country_id])   
    end 
end

app/views/elites/index.html.erb
<% content_for :content do %>
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <div class="row rowmega">
                    <div class="titolomega col-md-8 hidden-xs hidden-sm">&nbsp;</div>
                    <div class="titolomega2 hidden-xs col-md-4 hidden-sm">Elite groups</div>
                </div>
                <div class="hidden-xs">
                    <% @elites.each do |elite| %>
                        <%= link_to country_elite_path(:country_id => @country.id, :id => elite.id) do %>
                            <div class="group">
                                <table width="100%">
                                    <tr>
                                        <td width="200">
                                            <%= image_tag('groupimg.jpg', width: "200")%>
                                        </td>
                                        <td class="cella">
                                            <div class="titologroup"><%= elite.Name %></div>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        <% end %>
                    <% end %>
                </div>
            </div>
            <!-- 766px or smaller width -->
            <div class="row hidden-lg hidden-sm hidden-md">
                <div style="col-md-12">
                    <% @elites.each do |elite| %>
                        <%= link_to country_elite_path(:country_id => @country.id, :id => elite.id) do %>
                            <span class="thumb-info">
                                <span class="thumb-info-wrapper">
                                    <%= image_tag("groupimg.jpg", class: "img-responsive", alt: "") %>
                                    <span class="thumb-info-title">
                                        <span class="thumb-info-inner"> <%= elite.Name %></span>
                                    </span>
                                </span>
                            </span>
                        <% end %>
                    <% end %>
                </div>
            </div>          
        </div>
        <div style="padding-top:50px;"></div>
    </div>
<% end %>

app/views/elites/show.html.erb
<% content_for :title do %>
    <%= @elite.Name %>
<% end %>

<% content_for :content do %>
    <div class="row rowmega" id="overview">
        <div class="titolomega col-md-8 col-sd-8 hidden-sm hidden-xs">&nbsp;</div>
        <div class="titolomega2 hidden-xs hidden-sm col-md-4 col-sd-4"><%= @elite.Name %></div>
    </div>
    <div class="col-md-12">
        <div class="panel-group" id="accordion">
            <!-- Intro panel -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a class="accordion-toggle " data-panel="0" data-toggle="collapse" data-parent="#accordion" href="#collapse1One">
                            Intro
                        </a>
                    </h4>
                </div>
                <div id="collapse1One" class="accordion-body collapse in" role="group">
                    <div class="panel-body">
                        <p><%= @elite.Description %></p>
                    </div>
                </div>
            </div>
            <!-- Documents -->
            <div id="accordion0" class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a class="accordion-toggle" data-panel="1" data-toggle="collapse" data-parent="#accordion" href="#collapse1Two">
                            Documents
                        </a>
                    </h4>
                </div>
                <div id="collapse1Two" class="accordion-body collapse" role="group">
                    <div class="panel-body">
                        <table class="table table-striped">
                            <tbody>
                                <% @elite.files.each do |file| %>
                                    <tr>
                                        <td width="90%">
                                            <div class="doctitle">
                                                <%= link_to file.Name, "/files/#{file.FileName}" %>
                                            </div>
                                            <div class="docdesc"><%= truncate(@elite.Description, :length => 200) %></div>
                                        </td>
                                        <td>
                                            <%= link_to do %>
                                                <%= image_tag("pdf_doc.png") %>
                                            <% end %>
                                        </td>
                                    </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- People -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a class="accordion-toggle" data-panel="2" data-toggle="collapse" data-parent="#accordion" href="#collapse1Three">
                            People
                        </a>
                    </h4>
                </div>
                <div id="collapse1Three" class="accordion-body collapse in" role="group">
                    <div class="panel-body">
                        <div class="owl-carousel owl-theme stage-margin" style="overflow: hidden;" data-plugin-options='{"items": 4, "margin": 30, "loop": false, "nav": true, "dots": false, "stagePadding": 40}'>
                            <!-- Array HTML -->
                            <% @elite.people_elites.each do |elite_person| %>
                                <% person = Person.find(elite_person.PersonId) %>
                                <!-- Ouput person link -->
                                <div>
                                    <%= image_tag("person.jpg", class: "img-responsive", alt: person.get_full_name) %>
                                    <div class="personcarousel">
                                        <%= link_to( person.get_full_name, person_path(:id => elite_person.PersonId) ) %>
                                    </div>
                                </div>
                            <% end %>
                            <!-- To Remove -->
                            <!-- Test -->
                            <div>
                                <%= image_tag("person.jpg", class: "img-responsive", alt: Person.first.get_full_name) %>
                                <div class="personcarousel">
                                    <%= link_to( "1", person_path(:id => Elite.first.people_elites.first.PersonId) ) %>
                                </div>
                            </div>
                            <!-- Test -->
                            <div>
                                <%= image_tag("person.jpg", class: "img-responsive", alt: Person.first.get_full_name) %>
                                <div class="personcarousel">
                                    <%= link_to( "2", person_path(:id => Elite.first.people_elites.first.PersonId) ) %>
                                </div>
                            </div>
                            <!-- Test -->
                            <div>
                                <%= image_tag("person.jpg", class: "img-responsive", alt: Person.first.get_full_name) %>
                                <div class="personcarousel">
                                    <%= link_to( "3", person_path(:id => Elite.first.people_elites.first.PersonId) ) %>
                                </div>
                            </div>                        
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>